# Generated by Django 5.1.5 on 2025-01-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("hair", "Парикмахерские услуги"),
                    ("nail", "Маникюр"),
                    ("massage", "Массаж"),
                ],
                default=(("hair", "Парикмахерские услуги"),),
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
