# Generated by Django 5.1.5 on 2025-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_service_category_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("hair", "Парикмахерские услуги"),
                    ("nail", "Маникюр"),
                    ("massage", "Массаж"),
                ],
                default="hair",
                max_length=50,
            ),
        ),
    ]
