# Generated by Django 5.1.5 on 2025-01-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
