# Generated by Django 5.1.5 on 2025-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
