# Generated by Django 5.1.5 on 2025-01-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_customuser_profile_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile",
        ),
    ]
