# Generated by Django 5.1.5 on 2025-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_master_booking_master"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("master", "booking_date", "booking_time")},
        ),
    ]
