# Generated by Django 5.1.5 on 2025-02-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_master_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="master",
            name="role",
            field=models.CharField(default="Барбер", max_length=255),
        ),
        migrations.AddField(
            model_name="master",
            name="salon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="masters",
                to="users.salon",
            ),
        ),
    ]
