# Generated by Django 5.1.5 on 2025-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_customuser_is_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("owner", "Владелец")],
                default="user",
                max_length=10,
            ),
        ),
    ]
