# Generated by Django 5.1.5 on 2025-02-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("confirmed", "Подтверждено"),
                    ("completed", "Завершено"),
                    ("canceled", "Отменено"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
