# Generated by Django 5.1.5 on 2025-02-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.master",
            ),
        ),
    ]
